/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codeschool3

class App

fun main() {
//    val runner = DrewWordleRunner()
    val runner = KatherineWordleRunner()

    val words = loadFromJson()
    runner.playGame(words)//allPossibleWords, invalidWords)

    while (runner.playAgain()) {
        runner.playGame(words)
    }
}

class DrewWordleRunner() : WordleRunner {
    override fun playGame(words: WordleWords) {
        TODO("Not yet implemented")
    }
}